spring.application.name=yughistore
spring.datasource.username=yugy
spring.datasource.password=muto
spring.datasource.driver-class-name=org.postgresql.Driver

#used for hibernate performance tuning
spring.jpa.properties.hibernate.jdbc.batch_size=500
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.generate_statistics=false
spring.jpa.open-in-view=false
spring.jdbc.template.ignore-warnings=true

spring.ai.ollama.embedding.model=nomic-embed-text
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.ollama.chat.model=llama3.1:8b
spring.ai.ollama.init.chat.include=true

spring.ai.ollama.base-url=http://localhost:11434

spring.ai.vectorstore.pgvector.remove-existing-vector-store-table=false
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.ollama.init.pull-model-strategy=when_missing


spring.jpa.generate-ddl=true
#TODO set to update when going to predent
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
application.security.jwt.expiration=86400000
application.security.jwt.reset-expiration=900000
application.security.jwt.secret-key=2B7E151628AED2A6ABF7158809CF4F3C2B7E151628AED2A6ABF7158809CF4F3C
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=900MB

spring.datasource.url=jdbc:postgresql://localhost:5433/postgres


spring.docker.compose.file=./compose.yaml




