package com.cal.yughistore.model.enums;


public enum EnumCardType {
//    Main Deck Types
    EFFECT_MONSTER,
    FLIP_EFFECT_MONSTER,
    FLIP_TUNER_EFFECT_MONSTER,
    GEMINI_MONSTER,
    NORMAL_MONSTER,
    NORMAL_TUNER_MONSTER,
    PENDULUM_EFFECT_MONSTER,
    PENDULUM_EFFECT_RITUAL_MONSTER,
    PENDULUM_FLIP_EFFECT_MONSTER,
    PENDULUM_NORMAL_MONSTER,
    PENDULUM_TUNER_EFFECT_MONSTER,
    RITUAL_EFFECT_MONSTER,
    RITUAL_MONSTER,
    SPELL_CARD,
    SPIRIT_MONSTER,
    TOON_MONSTER,
    TRAP_CARD,
    TUNER_MONSTER,
    UNION_EFFECT_MONSTER,

//    Extra Deck Types
    FUSION_MONSTER,
    LINK_MONSTER,
    PENDULUM_EFFECT_FUSION_MONSTER,
    SYNCHRO_MONSTER,
    SYNCHRO_PENDULUM_EFFECT_MONSTER,
    SYNCHRO_TUNER_MONSTER,
    XYZ_MONSTER,
    XYZ_PENDULUM_EFFECT_MONSTER,

//    Other Types
    SKILL_CARD,
    TOKEN
}